media: media

content:
  - name: wiki
    label: Wiki Pages
    type: collection
    path: wiki
    subfolders: true
    view:
      fields: [title]
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text

  - name: petition
    label: Petition Signatures
    type: collection
    path: petition
    view:
      fields: [title]
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: rich-text
      - name: signatories
        label: Signatories
        type: object
        list: true
        fields:
          - name: name
            label: Name
            type: string
          - name: title_affiliation
            label: Title / Affiliation
            type: string
          - name: evidence_url
            label: Evidence URL
            type: string
          - name: evidence_label
            label: Evidence Link Text
            type: string
