media: media

content:
  - name: wiki
    label: Wiki Pages
    type: collection
    path: wiki
    subfolders: true
    view:
      fields: [title]
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
